name: Due Date Workflow
on:
  issues:
    types: [opened, edited, milestoned]
# on:
#   schedule:
#     - cron:  '0 * * * *'
jobs:
  Ubuntu:
    name: Add labels to issues
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Issue Due Dates Action
        uses: alexleventer/github-issue-due-dates-action@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}